[[redirects]]
  from = "/api/auth/*"
  to = "/api/auth/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://fanciful-cheesecake-b6d699.netlify.app"
  NEXTAUTH_URL = "https://fanciful-cheesecake-b6d699.netlify.app" 