[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://fanciful-cheesecake-b6d699.netlify.app" 